version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: deploy/stop.sh
      timeout: 200
      runas: root
  BeforeInstall:
    - location: deploy/before.sh
      timeout: 200
      runas: root
  AfterInstall:
    - location: deploy/afterinstall.sh
      timeout: 200
      runas: root
  ApplicationStart:
    - location: deploy/start.sh
      timeout: 200
      runas: root
  ValidateService:
    - location: deploy/validate.sh
      timeout: 200
      runas: root