version: 0.0
os: linux
hooks:
  ApplicationStop:
    - location: deploy/scripts/stop.sh
      timeout: 200
      runas: root
  BeforeInstall:
    - location: deploy/scripts/before.sh
      timeout: 200
      runas: root
  AfterInstall:
    - location: deploy/scripts/afterinstall.sh
      timeout: 2000
      runas: root
  ApplicationStart:
    - location: deploy/scripts/start.sh
      timeout: 200
      runas: root
  ValidateService:
    - location: deploy/scripts/validate.sh
      timeout: 200
      runas: root