version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  build:
    commands:
      - echo Build started on `date`
      - node --version
      - npm --version
      - npm install
      - npm run compile
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - deploy/**/*
    - dist/**/*
    - node_modules/**/*
    - package.json
    - appspec.yml
  discard-paths: no