pipeline {
    agent any
    
    environment {
        SSH_CREDENTIALS = credentials('06375e47-11d5-49ee-a096-94ba50ba035e') 
        // Replace with your SSH credentials ID - non root - 6b4b4214-61f8-4328-a565-f14961fb227c
        REMOTE_SERVER = '192.168.8.99' // Replace with your remote server hostname or IP
        REMOTE_PROJECT_FOLDER = 'Documents/website-imager'
        
    
    }
    
    stages {
        
        stage('Checkout Git Repository') {
            steps {
                // Specify the Git repository URL and branch
                checkout([$class: 'GitSCM', branches: [[name: 'main']], userRemoteConfigs: [[url: 'https://github.com/HaydenDekker/electronjs-website-imager/']]])
            }
        }

        stage('Copy and Deploy') {
            steps {
                sshagent(credentials: ['6b4b4214-61f8-4328-a565-f14961fb227c']) {
                    sh """
                        ssh -v -o StrictHostKeyChecking=no -l hayden ${REMOTE_SERVER} "if [ -z \"\$(ls -A ${REMOTE_PROJECT_FOLDER})\" ]; then echo 'Directory is empty'; else rm -r ${REMOTE_PROJECT_FOLDER}/*; fi"
                        scp -r ./dist hayden@${REMOTE_SERVER}:${REMOTE_PROJECT_FOLDER}
                        scp -r ./package.json hayden@${REMOTE_SERVER}:${REMOTE_PROJECT_FOLDER}
                        scp -r ./deploy/runtime_env hayden@${REMOTE_SERVER}:${REMOTE_PROJECT_FOLDER}
                    """
                }
            }
        }
    }
    
   
}