#!/bin/bash

echo "Starting x server"
nohup Xorg -config /etc/X11/xorg.conf.d/20-dummy.conf :3 &
echo "server started"

# ideally this is moved to build but was hard to get the correct electron version
npm install

DISPLAY=:3 npm run prod
